-- =============================================
-- Corrección grupos FIFA 2026 (sorteo 5 dic 2024)
-- Ejecutar en Supabase SQL Editor si ya tenés datos
-- =============================================

DELETE FROM public.teams;

INSERT INTO public.teams (name, code, flag_emoji, group_code, confederation) VALUES
('México',           'MEX', '🇲🇽', 'A', 'CONCACAF'),
('Sudáfrica',        'RSA', '🇿🇦', 'A', 'CAF'),
('Corea del Sur',    'KOR', '🇰🇷', 'A', 'AFC'),
('República Checa',  'CZE', '🇨🇿', 'A', 'UEFA'),
('Canadá',           'CAN', '🇨🇦', 'B', 'CONCACAF'),
('Bosnia y Herz.',   'BIH', '🇧🇦', 'B', 'UEFA'),
('Qatar',            'QAT', '🇶🇦', 'B', 'AFC'),
('Suiza',            'SUI', '🇨🇭', 'B', 'UEFA'),
('Brasil',           'BRA', '🇧🇷', 'C', 'CONMEBOL'),
('Marruecos',        'MAR', '🇲🇦', 'C', 'CAF'),
('Haití',            'HAI', '🇭🇹', 'C', 'CONCACAF'),
('Escocia',          'SCO', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'C', 'UEFA'),
('Estados Unidos',   'USA', '🇺🇸', 'D', 'CONCACAF'),
('Paraguay',         'PAR', '🇵🇾', 'D', 'CONMEBOL'),
('Australia',        'AUS', '🇦🇺', 'D', 'AFC'),
('Turquía',          'TUR', '🇹🇷', 'D', 'UEFA'),
('Alemania',         'GER', '🇩🇪', 'E', 'UEFA'),
('Curazao',          'CUW', '🇨🇼', 'E', 'CONCACAF'),
('Costa de Marfil',  'CIV', '🇨🇮', 'E', 'CAF'),
('Ecuador',          'ECU', '🇪🇨', 'E', 'CONMEBOL'),
('Países Bajos',     'NED', '🇳🇱', 'F', 'UEFA'),
('Japón',            'JPN', '🇯🇵', 'F', 'AFC'),
('Suecia',           'SWE', '🇸🇪', 'F', 'UEFA'),
('Túnez',            'TUN', '🇹🇳', 'F', 'CAF'),
('España',           'ESP', '🇪🇸', 'G', 'UEFA'),
('Argelia',          'ALG', '🇩🇿', 'G', 'CAF'),
('Nigeria',          'NGA', '🇳🇬', 'G', 'CAF'),
('Croacia',          'CRO', '🇭🇷', 'G', 'UEFA'),
('Argentina',        'ARG', '🇦🇷', 'H', 'CONMEBOL'),
('Chile',            'CHI', '🇨🇱', 'H', 'CONMEBOL'),
('Iraq',             'IRQ', '🇮🇶', 'H', 'AFC'),
('Ucrania',          'UKR', '🇺🇦', 'H', 'UEFA'),
('Francia',          'FRA', '🇫🇷', 'I', 'UEFA'),
('Arabia Saudita',   'KSA', '🇸🇦', 'I', 'AFC'),
('Camerún',          'CMR', '🇨🇲', 'I', 'CAF'),
('Costa Rica',       'CRC', '🇨🇷', 'I', 'CONCACAF'),
('Inglaterra',       'ENG', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'J', 'UEFA'),
('Irán',             'IRN', '🇮🇷', 'J', 'AFC'),
('Venezuela',        'VEN', '🇻🇪', 'J', 'CONMEBOL'),
('Senegal',          'SEN', '🇸🇳', 'J', 'CAF'),
('Portugal',         'POR', '🇵🇹', 'K', 'UEFA'),
('Bélgica',          'BEL', '🇧🇪', 'K', 'UEFA'),
('Colombia',         'COL', '🇨🇴', 'K', 'CONMEBOL'),
('Uruguay',          'URU', '🇺🇾', 'K', 'CONMEBOL'),
('Serbia',           'SRB', '🇷🇸', 'L', 'UEFA'),
('Honduras',         'HON', '🇭🇳', 'L', 'CONCACAF'),
('Uzbekistán',       'UZB', '🇺🇿', 'L', 'AFC'),
('Ghana',            'GHA', '🇬🇭', 'L', 'CAF');
